stages:
  - test
  - build
  - deploy

.deploy_template: &deploy_definition
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - echo "About to copy to EOS"
    - echo $EOS_ACCOUNT_USERNAME
    - klist
    - /sbin/deploy-eos

.test:
  stage: test
  image: alpine:3.5
  script:
    # install additional Alpine packages
    - apk add --update bash git make
    
deploy_staging:
  variables:
    EOS_PATH: "$WEBSITE_PATH/_staging/$CI_COMMIT_REF_NAME"
    CI_OUTPUT_DIR: "."
  <<: *deploy_definition
  # except:
  #  - master
