stages:
  - test
  - deploy

.deploy_template: &deploy_definition
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - echo "About to copy to EOS"
    - pwd
    - echo $EOS_ACCOUNT_USERNAME
    - kinit="/usr/bin/kinit"
    - echo "$EOS_ACCOUNT_PASSWORD" | $kinit "$EOS_ACCOUNT_USERNAME@CERN.CH" 2>&1 >/dev/null
    - /usr/bin/klist
    - echo "$EOS_DIR/$EOS_PATH/"
    #- /usr/bin/xrdcp --force --recursive --silent --path "$CI_OUTPUT_DIR/*.html" "root://eosuser//eos/user/e/emoyse/www/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "index.html" "$EOS_DIR/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "geom_display.html" "$EOS_DIR/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "jsdisplay_ATLAS.html" "$EOS_DIR/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "jsdisplay_CTD.html" "$EOS_DIR/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "js" "$EOS_DIR/$EOS_PATH/js/"
    - /usr/bin/xrdcp --force --recursive --silent --path "lib" "$EOS_DIR/$EOS_PATH/lib/"
    - /usr/bin/xrdcp --force --recursive --silent --path "img" "$EOS_DIR/$EOS_PATH/img/"
    #- /sbin/deploy-eos

.test:
  stage: test
  image: alpine:3.5
  script:
    # install additional Alpine packages
    - apk add --update bash git make
    
deploy_staging:
  variables:
    EOS_PATH: "_staging/$CI_COMMIT_REF_NAME"
  <<: *deploy_definition
  # except:
  #  - master
  environment:
    name: staging/$CI_COMMIT_REF_NAME
    url: emoyse.web.cern.ch/emoyse/WebEventDisplay/_staging/$CI_COMMIT_REF_NAME
    
remove_staging:
  stage: deploy
  variables:
    # don't checkout code from git (to prevent checking out deleted branches)
    GIT_STRATEGY: none
    EOS_PATH: "_staging/$CI_COMMIT_REF_NAME"
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  before_script:
    - kinit="/usr/bin/kinit"
    - echo "$EOS_ACCOUNT_PASSWORD" | $kinit "$EOS_ACCOUNT_USERNAME@CERN.CH" 2>&1 >/dev/null
  script:
    - /usr/bin/klist
    - /usr/bin/xrdfs rmdir "$EOS_DIR/$EOS_PATH/"
  after_script:
    - kdestroy
  environment:
    name: production
    action: stop

deploy_production:
  stage: deploy
  variables:
    EOS_PATH: ""
  <<: *deploy_definition
  only:
    - master
  when: manual
  environment:
    name: production
    url: https://emoyse.web.cern.ch/emoyse/WebEventDisplay
    on_stop: remove_staging
    

