stages:
  - test
  - build
  - deploy

.deploy_template: &deploy_definition
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - echo "About to copy to EOS"
    - pwd
    - echo $EOS_ACCOUNT_USERNAME
    - kinit="/usr/bin/kinit"
    - echo "$EOS_ACCOUNT_PASSWORD" | $kinit "$EOS_ACCOUNT_USERNAME@CERN.CH" 2>&1 >/dev/null
    - /usr/bin/klist
    - echo "$CI_OUTPUT_DIR/"
    - echo "$EOS_DIR/$EOS_PATH/"
    #- /usr/bin/xrdcp --force --recursive --silent --path "$CI_OUTPUT_DIR/*.html" "root://eosuser//eos/user/e/emoyse/www/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "index.html" "$EOS_DIR/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "js" "$EOS_DIR/$EOS_PATH/js/"
    - /usr/bin/xrdcp --force --recursive --silent --path "img" "$EOS_DIR/$EOS_PATH/img/"
    #- /sbin/deploy-eos

.test:
  stage: test
  image: alpine:3.5
  script:
    # install additional Alpine packages
    - apk add --update bash git make
    
deploy_staging:
  variables:
    EOS_PATH: "$WEBSITE_PATH/_staging/$CI_COMMIT_REF_NAME"
    CI_OUTPUT_DIR: "."
  <<: *deploy_definition
  # except:
  #  - master
  environment:
    name: staging/$CI_COMMIT_REF_NAME
    url: https://emoyse.web.cern.ch/emoyse/_staging/$CI_COMMIT_REF_NAME
    on_stop: remove_staging
    
remove_staging:
  stage: deploy
  variables:
    # don't checkout code from git (to prevent checking out deleted branches)
    GIT_STRATEGY: none
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  before_script:
    - echo "$EOS_ACCOUNT_PASSWORD" | $kinit "$EOS_ACCOUNT_USERNAME@CERN.CH" 2>&1 >/dev/null
  script:
    - STAGING_DIR="$WEBSITE_FULL_DIR\\_staging"
    - DELETEME_DIR="$WEBSITE_FULL_DIR\\_staging\\_deleteme"
  after_script:
    - kdestroy
  when: manual
  environment:
    name: staging/$CI_COMMIT_REF_NAME
    action: stop

