stages:
  - test
  - build
  - deploy

.deploy_template: &deploy_definition
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - echo "About to copy to EOS"
    - echo $EOS_ACCOUNT_USERNAME
    - kinit="/usr/bin/kinit"
    - echo "$EOS_ACCOUNT_PASSWORD" | $kinit "$EOS_ACCOUNT_USERNAME@CERN.CH" 2>&1 >/dev/null
    - /usr/bin/klist
    - echo "$CI_OUTPUT_DIR/"
    - echo "$EOS_MGM_URL/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "$CI_OUTPUT_DIR/*.html" "root://eosuser.cern.ch/e/emoyse/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "$CI_OUTPUT_DIR/js" "root://eosuser.cern.ch/e/emoyse/$EOS_PATH/"
    - /usr/bin/xrdcp --force --recursive --silent --path "$CI_OUTPUT_DIR/img" "root://eosuser.cern.ch/e/emoyse/$EOS_PATH/"
    #- /sbin/deploy-eos

.test:
  stage: test
  image: alpine:3.5
  script:
    # install additional Alpine packages
    - apk add --update bash git make
    
deploy_staging:
  variables:
    EOS_PATH: "$WEBSITE_PATH/_staging/$CI_COMMIT_REF_NAME"
    CI_OUTPUT_DIR: "."
  <<: *deploy_definition
  # except:
  #  - master
