dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

before_cache:
  - cd packages/phoenix-event-display
  - npm link
  - cd ../phoenix-app
  - cd ../../

cache:
  directories:
    - ./packages/phoenix-app/node_modules

before_install:
  - cd packages/phoenix-app
  - npm install install-subset

install: true
  - npx subset install test
  - npm link "@phoenix/event-display"

script:
  - npm run test:coverage -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  # Bug with Angular 10 (https://github.com/angular/protractor/issues/5460)
  #- npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

after_success:
  - npm run coveralls
