dist: trusty
sudo: false
 
language: node_js
node_js:
  - 10
 
addons:
   chrome: stable

install:
  - npm ci
 
script:
  - npm install
  - yarn all_tests #Uses yarn to run our custom script all_tests

