dist: trusty
sudo: false
 
language: node_js
node_js:
  - 10
 
addons:
   chrome: stable

install:
  - npm ci
 
script:
  - npm run install
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
