dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

cache:
  directories:
    - ./packages/phoenix-ng/node_modules
    - ./packages/phoenix-event-display/node_modules

install:
  - npm install lerna --global
  - npm run install:dependencies

script:
  - cd ./packages/phoenix-ng
  - npm run test:coverage -- --no-progress --browsers=ChromeHeadlessCI
  - cd ../..
  # Set up surge and deploy for PR
  - if [ "$TRAVIS_PULL_REQUEST" != false ]; then npm install surge --global; fi
  - if [ "$TRAVIS_PULL_REQUEST" != false ]; then npm run deploy:web; fi
  # Deploy the PR to surge
  - if [ "$TRAVIS_PULL_REQUEST" != false ]; then chmod +x ./scripts/pr_deploy.sh; ./scripts/pr_deploy.sh; fi

after_success:
  - cd ./packages/phoenix-ng
  - npm run coveralls
