name: Phoenix

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@main
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Phoenix
        run: |
          npm install --global yarn lerna
          yarn install:dependencies

      - name: Run Tests
        run: yarn test:coverage

      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: './packages/phoenix-event-display/coverage/lcov.info'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          chmod +x ./scripts/pr_deploy.sh
          ./scripts/pr_deploy.sh
